apiVersion: vsso.cz/v1
kind: VaultSecret
metadata:
  name: my-db-pass
  namespace: sandbox-sit
  annotations:
    vault.hashicorp.com/path: dbos-sit
    vault.hashicorp.com/service-account: default
    vault.hashicorp.com/refresh-time: 2m
  labels:
    app: example
spec:
  type: Opaque
  stringData:
    username: "<db_user>"
    password: "<db_pass>"
